[package]
name = "agent-chess-arena-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.agent-chess-arena]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.54.0"
default-features = false

